[[projects]]
repo = "https://github.com/getsentry/relay.git"
root = ""
subprojects = ["relay-common"]

[[projects]]
repo = "https://github.com/getsentry/symbolicator.git"
root = ""
subprojects = ["crates/symbolicator"]

[[projects]]
repo = "https://github.com/internetarchive/fatcat.git"
root = "rust"
subprojects = []

[[projects]]
repo = "https://github.com/mozilla/classify-client.git"
root = ""
subprojects = []